import Feedback from "./Feedback";

export default class Answer {
  private _modelMessage: string;
  private _answer: string;
  private _feedback: string;
  private _isCorrect: boolean;

  private constructor(
    modelMessage: string,
    answer: string,
    feedback: string,
    isCorrect: boolean,
  ) {
    this._modelMessage = modelMessage;
    this._answer = answer;
    this._feedback = feedback;
    this._isCorrect = isCorrect;
  }

  public static build(userAnswer: string, feedback: Feedback): Answer {
    // Extract feedback, expectedAnswer and isCorrect from the raw feedback generated by the model
    return new Answer(
      feedback.message,
      userAnswer,
      feedback.feedback,
      feedback.isCorrect,
    );
  }

  public toView() {
    return {
      answer: this._answer,
      feedback: this._feedback,
      isCorrect: this._isCorrect,
    };
  }

  public get modelMessage(): string {
    return this._modelMessage;
  }

  public get answer(): string {
    return this._answer;
  }

  public get feedback(): string {
    return this._feedback;
  }

  public get isCorrect(): boolean {
    return this._isCorrect;
  }
}
