import assert from "assert";
import { z } from "zod";

export default class Answer {
  private _answer: string;
  private _feedback: string;
  private _isCorrect: boolean;
  private _expectedAnswer: string;

  private constructor(
    answer: string,
    feedback: string,
    isCorrect: boolean,
    expectedAnswer: string,
  ) {
    this._answer = answer;
    this._feedback = feedback;
    this._isCorrect = isCorrect;
    this._expectedAnswer = expectedAnswer;
  }

  public static parseFeedbackFromAi(
    userAnswer: string,
    message: string,
  ): Answer {
    // Extract feedback, expectedAnswer and isCorrect from the raw feedback generated by the model
    const regex = /<=>(.+)<\+>(.+)<\+>(.+)<=>/m;
    const match = message.match(regex);
    assert(match, "Invalid feedback format");

    const [_, feedback, expectedAnswer, isCorrectStr] = match;

    const validatedMatch = z
      .object({
        feedback: z.string(),
        isCorrectStr: z.enum(["CORRECT", "INCORRECT"]),
        expectedAnswer: z.string(),
      })
      .parse({
        feedback,
        expectedAnswer,
        isCorrectStr,
      });

    const validatedFeedback = validatedMatch.feedback;
    const validatedIsCorrect = validatedMatch.isCorrectStr === "CORRECT";
    const validatedExpectedAnswer = validatedMatch.expectedAnswer;

    if (
      !validatedIsCorrect &&
      validatedExpectedAnswer.toLowerCase() === userAnswer.toLowerCase()
    ) {
      throw new Error("Model gave an incorrect expectedAnswer");
    }

    return new Answer(
      userAnswer,
      validatedFeedback,
      validatedIsCorrect,
      validatedExpectedAnswer,
    );
  }

  public toView() {
    return {
      answer: this._answer,
      feedback: this._feedback,
      isCorrect: this._isCorrect,
      expectedAnswer: this._expectedAnswer,
    };
  }

  public get answer(): string {
    return this._answer;
  }

  public get feedback(): string {
    return this._feedback;
  }

  public get isCorrect(): boolean {
    return this._isCorrect;
  }

  public get expectedAnswer(): string {
    return this._expectedAnswer;
  }
}
