import Feedback from "./Feedback";

export default class Answer {
  private _answer: string;
  private _feedback: Feedback;

  private constructor(answer: string, feedback: Feedback) {
    this._answer = answer;
    this._feedback = feedback;
  }

  public static build(userAnswer: string, feedback: Feedback): Answer {
    // Extract feedback, expectedAnswer and isCorrect from the raw feedback generated by the model
    return new Answer(userAnswer, feedback);
  }

  public toView() {
    return {
      answer: this._answer,
      feedback: this._feedback.toView(),
    };
  }

  public get answer(): string {
    return this._answer;
  }

  public get feedback(): Feedback {
    return this._feedback;
  }
}
